# PostgreSQL - z Render
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka - Aiven SSL
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
kafka.ssl.ca-cert=${KAFKA_CA_CERT}
kafka.ssl.client-cert=${KAFKA_CLIENT_CERT}
kafka.ssl.client-key=${KAFKA_CLIENT_KEY}

# Actuator
management.endpoints.web.exposure.include=health,info