# App
spring.application.name=order-notifier
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ordernotifier
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=order-notifier-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.auto-offset-reset=earliest

# Rate limiting
app.rate-limit.api.capacity=10
app.rate-limit.api.refill-tokens=10
app.rate-limit.api.refill-duration-seconds=60

app.rate-limit.email.capacity=10
app.rate-limit.email.refill-tokens=10
app.rate-limit.email.refill-duration-seconds=1

# Actuator
management.endpoints.web.exposure.include=health,info